### ISSUE TITLE
Question about fGOT and GOT

### ISSUE THREAD

**Issue by HelloWorldLTY** [Hermina/fGOT#1]
Hi, I wonder if I intend to measure the distance of two graphs with known and informative labels, is it possible for me to use this method? I think based on the description of got paper and wess distance, this approach does not include the node information. Thanks.

**Comment by Hermina** [comment]
Hi, there are a few ways node labels could be added, but they are not included in the current solution. Depending on your application, I would suggest adding node labels to the original distributions that you create and thus modifying the filtered distributions directly. Another good approach could be adding an additional term to the optimisation problem in the form of the Wasserstein distance between labels (or another additional term you find appropriate for your application). Hope that helps and keep me posted if you end up trying and exploring it!
